/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./components/charts/BarChart.vue')['default']
    BaseChart: typeof import('./components/charts/BaseChart.vue')['default']
    LineChart: typeof import('./components/charts/LineChart.vue')['default']
    NavIcon: typeof import('./components/common/NavIcon.vue')['default']
    PieChart: typeof import('./components/charts/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafeMarkdown: typeof import('./components/common/SafeMarkdown.vue')['default']
    TableSettings: typeof import('./components/common/TableSettings.vue')['default']
  }
}
